#python

#python
print('afaafafffafaf')



print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")

print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")
print("ashok kumar")

#python
